<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AppGuard.Core</AssemblyName>
    <RootNamespace>AppGuard.Core</RootNamespace>
    <Version>0.18.3</Version>
  </PropertyGroup>
</Project>
